### PR TITLE
Fix gradlew flag and fix updating mature plants

### PR DESCRIPTION
**Pull request by afdw**

### CODE REVIEW

**Comment by afdw** [comment]
@lumien231 Is there any progress on this?

**Comment by Pythonic-Rainbow** [comment]
@afdw u dead yet?

**Comment by afdw** [comment]
No. And I think I can update the PR if you want.

**Comment by Pythonic-Rainbow** [comment]
Do you still remember what you wrote 2 years ago? 😂 @afdw

**Comment by Pythonic-Rainbow** [comment]
Jesus its been almost a year

**Pull request closed without merging**
